### ISSUE TITLE
Small details: milliseconds & undefined vars

### ISSUE THREAD

**Issue by JillElaine** [josebalius/jquery-idleTimeout#1]
sessionAlive: 30000 = 3 seconds, not 10 minutes; also incorrect on philpalmieri parent

autoLogoutMessage, autoLogoutStayLoggedIn & autoLogoutTitle are undefined

Will comment on functionality soon. Thank you!

**Comment by josebalius** [comment]
@JillElaine,

Good points, i'll change the code to pass those variables in as init options instead of sitting in the global scope.

Thanks

Jose

**Comment by josebalius** [comment]
@JillElaine 

I have committed the fixes for this issue.

Jose

**Comment by JillElaine** [comment]
Awesome. Thank you!
