### ISSUE TITLE
Test of functionality with Mozilla Firefox

### ISSUE THREAD

**Issue by JillElaine** [josebalius/jquery-idleTimeout#2]
Firefox v.22. 
## With multipleTabs: false

Single, inactive tab: dialog 'timeout' warning box appears as expected. 
Multiple tabs, one active, one inactive: dialog 'timeout' warning box appears on inactive tab, dialog box cannot be seen on active tab. Inactive tab redirects to 'redirect_url' as expected. Active tab does not 'timeout': user not notified of 'timeout'. This is all expected behavior with multipleTabs: false, in my opinion.
## With multipleTabs: true

Single, inactive tab: dialog 'timeout' warning box appears as expected. 
Multiple tabs, one active, one inactive: dialog 'timeout' warning box does not appear: 'timeout' does not happen on any tab, the expected behavior.
Multiple tabs, all inactive: dialog 'timeout' warning box appears on all tabs. Click to close dialog box on top tab (and prevent timeout) does not immediately close dialog box(es) on other tabs. However, the other tabs do not timeout and the extraneous dialog box(es) on the other tabs are closed without further intervention via the 'redirect' function in the code. All reasonable behavior.
## What is considered 'activity'

Only mouse clicks are detected. Mouse moves or keyboard presses, such as filling out a form while moving between fields with the tab key is not detected as activity. Would be improved functionality to detect key press events, and ++ to detect mouse moves.

Note:
A mouse click anywhere on the window (not just on a dialog box) will prevent timeout, but does not close dialog box. Click the dialog X or button to close dialog (normal behavior).

**Comment by josebalius** [comment]
@JillElaine 

Thanks for this valuable feedback.

I will share this with my team and we will see what enhancements we can make to improve it based on this. You are always welcomed to put in a pull request and contribute to the project :)

Jose

**Comment by JillElaine** [comment]
I would love to help with this...good learning for me. Working on some pseudo-code. 
I would like to add a var to configure the events to detect.
Example:

``` javascript
multipleTabs: true,
customCallback: false,
listenEvents: 'click keypress wheel mousewheel scroll'
```

http://www.quirksmode.org/dom/events/
https://developer.mozilla.org/en-US/docs/Web/Reference/Events

**Comment by josebalius** [comment]
@JillElaine 

That sounds great! You should definitely do it, i know we would use it here internally. So give it a shot and let me know please!

The only thing I would say is that instead of doing:

``` javascript
listenEvents: 'click keypress wheel mousewheel scroll'
```

I would use an Array instead of a string, so:

``` javascript
listenEvents: ['click', 'keypress', 'wheel', 'mousewheel', 'scroll']
```

Let me know! :)

Jose

**Comment by JillElaine** [comment]
Created a fork here: https://github.com/JillElaine/jquery-idleTimeout

I know I have some bugs to work out. Would appreciate mentoring, feedback, testing, etc. Thank you.

**Comment by josebalius** [comment]
@JillElaine 

Great job, looks great. I'll have a play with it this weekend :)

Jose

**Comment by JillElaine** [comment]
Pushed new commit this morning. Fixed big issue with monitoring of multiple windows & tabs.

**Comment by josebalius** [comment]
@JillElaine I am going to close this now since you seem to have fixed all of the issues. Again awesome job with this, thank you!
